apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: app-example
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: app-example
    spec:
      containers:
      - name: app-example
        image: gcr.io/PROJECT_ID/APPLICATION_NAME:TAG
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 100m
---
apiVersion: v1
kind: Service
metadata:
  name: app-example-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 5000
  selector:
    app: app-example
